<?php

namespace App\Http\Controllers;

use App\Services\AuditLogger;
use App\Services\OperationalReportService;
use App\Services\SimplePdfService;
use App\Services\XlsxService;
use App\Support\PublicError;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ReportController extends Controller
{
    public function index(Request $request, OperationalReportService $reports)
    {
        return view('reports.index', $reports->page($request));
    }

    public function export(
        Request $request,
        string $format,
        OperationalReportService $reports,
        XlsxService $xlsx,
        SimplePdfService $pdf
    ) {
        abort_unless(in_array($format, ['xlsx', 'pdf', 'csv'], true), 404);

        $payload = $reports->exportPayload($request);
        $filename = $this->filename($payload['tab'], $format);
        $preamble = $this->preamble($payload);
        $exportRows = $payload['all_rows']->map(fn ($row) => array_values((array) $row))->all();
        $headers = $payload['headers'];
        $totals = $payload['totals'];

        try {
            if ($format === 'xlsx') {
                $path = $xlsx->exportReport($preamble, $headers, $exportRows, $filename, $totals);
                AuditLogger::log('Exported', 'Reports', 'Exported '.$payload['title'].' as Excel', null, $request);

                return response()->download($path, $filename)->deleteFileAfterSend(true);
            }

            if ($format === 'pdf') {
                $insight = is_string($payload['insight'] ?? null) ? $payload['insight'] : null;
                $pdfRows = $exportRows;
                if (is_array($totals)) {
                    $pdfRows[] = array_values($totals);
                }
                $binary = $pdf->render($payload['title'], $preamble, $headers, $pdfRows, $insight);
                AuditLogger::log('Exported', 'Reports', 'Exported '.$payload['title'].' as PDF', null, $request);

                return response($binary, 200, [
                    'Content-Type' => 'application/pdf',
                    'Content-Disposition' => 'attachment; filename="'.$filename.'"',
                ]);
            }

            AuditLogger::log('Exported', 'Reports', 'Exported '.$payload['title'].' as CSV', null, $request);

            return $this->csvDownload($filename, $headers, $exportRows, is_array($totals) ? $totals : null);
        } catch (\Throwable $exception) {
            return back()->with('error', PublicError::failed('Export', $exception));
        }
    }

    /**
     * @param  array<string, mixed>  $payload
     * @return list<string>
     */
    private function preamble(array $payload): array
    {
        $lines = [
            (string) $payload['title'],
            'Generated: '.$payload['generated_at']->format('M d, Y g:i A'),
            'Generated by: '.(string) $payload['generated_by'],
        ];
        foreach ($payload['applied_filters'] as $label => $value) {
            $lines[] = $label.': '.$value;
        }

        return $lines;
    }

    /**
     * @param  list<string>  $headers
     * @param  list<list<mixed>>  $rows
     * @param  list<mixed>|null  $totals
     */
    private function csvDownload(string $filename, array $headers, array $rows, ?array $totals): StreamedResponse
    {
        return response()->streamDownload(function () use ($headers, $rows, $totals) {
            $handle = fopen('php://output', 'w');
            if ($handle === false) {
                return;
            }
            fputcsv($handle, $headers);
            foreach ($rows as $row) {
                fputcsv($handle, array_values($row));
            }
            if (is_array($totals) && $totals !== []) {
                fputcsv($handle, array_values($totals));
            }
            fclose($handle);
        }, $filename, [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    private function filename(string $tab, string $format): string
    {
        return $tab.'-'.now()->format('Y-m-d').'.'.$format;
    }
}
